---
- name: create local docker registry
  become: yes
  become_user: docker
  docker_swarm_service:
    name: registry
    image: registry:2
    publish:
      - published_port: 5000
        target_port: 5000
