---
- name: update hosts file
  become: yes
  lineinfile:
    path: /etc/hosts
    regexp: ".*{{ item }}$"
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}"   
    state: present
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: "{{ groups['dockerNodes'] }}"

- name: comment out IPv6 mapping for localhost
  become: yes
  replace:
    path: /etc/hosts
    regexp: "^::1"
    replace: "#::1"
